name: esotranspiler
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-28.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project
  url_launcher: ^6.3.2

flutter: 
  uses-material-design: true

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
